### ISSUE TITLE
Running the workflow removes rust override set up by previous `actions-rs/toolchain` call

### ISSUE THREAD

**Issue by bugadani** [esp-rs/xtensa-toolchain#10]
My workflow would set up a nightly Rust and then the Xtensa port, something like this:

```yml
      - name: Install nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: nightly
          override: true
          components: rust-src

      - name: Install Rust for Xtensa
        uses: esp-rs/xtensa-toolchain@v1.3
        with:
          version: "1.63.0.0"
          buildtargets: esp32
```

`xtensa-toolchain` removes the override so later steps use stable rustc instead of nightly.

**Comment by jessebraham** [comment]
My memory is a little fuzzy on this, but this was changed in order to handle `rust-toolchain.toml` files specifying the `esp` channel, which obviously does not exist for the official compiler. You can see [this commit](https://github.com/esp-rs/xtensa-toolchain/commit/9de5c646b53804bb3d042eeae6cbd9a4fd433dd9) is where the changes were made.

I can try to play around with this next week and see if I can get it working without using overrides.

**Comment by bugadani** [comment]
I'm using nightly to run rustfmt and clippy, and even if I flip the order of the two workflow steps, the tools don't get picked up correctly. Due to this I went back to my custom 4-liner install script instead of this workflow for now.

I guess a "remove overrides" option would help, but I might be a special case.

**Comment by SergioGasquez** [comment]
Hi @bugadani! Is, by any chance, the repository where you are using the CI open? If so, would you mind sharing it?

**Comment by bugadani** [comment]
@SergioGasquez sorry it's closed :(

**Comment by SergioGasquez** [comment]
Would you mind testing with:
```
      - name: Install nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: nightly
          override: true
          components: rust-src

      - name: Install Rust for Xtensa
        uses: SergioGasquez/xtensa-toolchain@main
        with:
          version: "1.63.0.0"
          buildtargets: esp32
          override: false
```
