### ISSUE TITLE
Failed to detect version of Xtensa Rust, reinstalling it

### ISSUE THREAD

**Issue by rowanfr** [esp-rs/xtensa-toolchain#29]
Whenever I try to use the default action from the ESP no-std template with `act` I keep running into the repeated issue:
```
| [info]: Installing 'rust' component for Xtensa Rust toolchain
| [info]: Uninstalling Xtensa Rust toolchain
| [warn]: Installation for 'Xtensa Rust' failed, retrying
| [warn]: Failed to detect version of Xtensa Rust, reinstalling it
| [info]: Uninstalling Xtensa Rust toolchain
| [info]: Installing Xtensa Rust 1.82.0.3 toolchain
```
This is even after I specify a version in the YAML file such as `version: "1.82.0.3"` or earlier or leave it undefined. Any ideas on what's causing this or how to solve it?

**Comment by rowanfr** [comment]
This seems to be related to the code snippet here:
https://github.com/esp-rs/espup/blob/c0801b9f0acf5e1355b9400223eed45b598f81fa/src/toolchain/rust.rs#L197-L214

where the rustc version is not succeeding for whatever reason

**Comment by rowanfr** [comment]
For further clarification as well the YAML job file is:
```yaml
name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: build
            args: --release
          - command: fmt
            args: --all -- --check --color always
          - command: clippy
            args: --all-features --workspace -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32
          ldproxy: false
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
```

and the used command is `act -s GITHUB_TOKEN=private_token`
