### ISSUE TITLE
Add option to install Extended LLVM installation (default: false)

### ISSUE THREAD

**Issue by AnthonyGrondin** [esp-rs/xtensa-toolchain#40]
`espup` supports installing the full espressif's fork LLVM installation using the following flag:

```
  -e, --extended-llvm
          Extends the LLVM installation.

          This will install the whole LLVM instead of only installing the libs.
```

This action should support having an option to enable the installation of the full LLVM, for CI that needs to build libraries with the LLVM toolchain.

Currently, a user has to do the following to get the full extended llvm installed in CI

```yml
- name: Install Rust for Xtensa
  uses: esp-rs/xtensa-toolchain@v1.5

- name: Install full Espressif LLVM installation
  run: $HOME/.cargo/bin/espup install -l debug --extended-llvm
```

With the added option, a user could do the following, and it would be supported on both Windows and Linux / MacOS:
```yml
- name: Install Rust for Xtensa
  uses: esp-rs/xtensa-toolchain@v1.5
  with:
    extended-llvm: true
```

It goes without saying that this feature should be false by default, for parity with espup, and also because its heavier to install the full extended installation when we don't need it.
